repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: black
        language: system
        types: [python]

      - id: isort
        name: Isort
        entry: isort
        language: system
        types: [python]

      - id: flake8
        name: Flake8
        entry: flake8
        language: system
        types: [python]
      
      - id: mypy
        name: Mypy
        entry: mypy
        language: system
        types: [python]
