services:
  magneto-api:
    build:
      context: .
      dockerfile: dockerfile.local
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - .:/home/magnetoapp/api
    environment:
      - PYTHONUNBUFFERED=1
