name: CI Tests - MagnetoApp

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.4"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run linters and type checkers
        run: |
          echo "Running flake8..."
          poetry run flake8 app

          echo "Running black..."
          poetry run black --check app

          echo "Running isort..."
          poetry run isort --check-only app

          echo "Running mypy..."
          poetry run mypy app

      - name: Run tests with coverage
        env:
          MAGNETO_DNA_DATA_TABLE: "some-table-name"
          AWS_ACCESS_KEY_ID: "some-key-id"
          AWS_SECRET_ACCESS_KEY: "some-secret-access-key"
          AWS_DEFAULT_REGION: "us-east-1"
        run: poetry run pytest --cov=app --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
